#!perl

# AUTHORITY
# DATE
# DIST
# VERSION

use 5.010001;
use strict;
use warnings;

use Perinci::CmdLine::Any;

our %SPEC;

my $prefix = '/App/idxdb/';

Perinci::CmdLine::Any->new(
    url => $prefix,
    subcommands => {
        'update'     => {url => "${prefix}update"},
        'ownership'  => {url => "${prefix}ownership"},
        'daily'      => {url => "${prefix}daily"},
    },
    log => 1,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

To update data:

 % idxdb update

To see the legends for ownership field names (e.g. ForeignIB = foreign bank):

 % idxdb ownership --legend

To see ownership (e.g. % foreign/local) of some stock through time:

 % idxdb ownership BBRI
 % idxdb ownership --fields-all BBRI --date-start 2020-01-01 --date-end 2020-09-30
 % idxdb ownership --fields-foreign-total --6month --graph BBNI

To graph ownership composition (% foreign bank, foreign total, local bank, etc)
of some stock:

 % idxdb graph-ownership-composition BBRI

To see a table of daily trading summary of some stock:

 % idxdb table-daily-trading-summary BBRI

To graph accumulated foreign net buy of some stock in the last year:

 % idxdb graph-daily-trading-summary --field AccumForeignNetBuy --year BBRI


=head1 DESCRIPTION

B<NOTE: EARLY RELEASE, ONLY A FEW SUBCOMMANDS HAVE BEEN IMPLEMENTED.>

This utility lets you load some data like IDX's daily trading summary (stock
summary), list of stocks, and KSEI's monthly ownership into a SQLite database
and perform some SQL queries against it.

Keywords: stock trading, Indonesian Stock Exchange, securities analysis.


=head1 SEE ALSO

L<Finance::SE::IDX>

L<Finance::ID::KSEI>
